name: events_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1
  dropdown_button2: ^2.3.9

  location: ^8.0.0
  cloud_firestore: ^5.6.7
  flutter_localizations:
    sdk: flutter  
  intl: any
  google_maps_flutter: ^2.12.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/categories_images/
