// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKfQvgk1ZesbHGw2VxVMJSqyUQHjYxzVs',
    appId: '1:361353348856:web:9146b3c720b60ea4ef5d0d',
    messagingSenderId: '361353348856',
    projectId: 'events-manager-f5341',
    authDomain: 'events-manager-f5341.firebaseapp.com',
    storageBucket: 'events-manager-f5341.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WIeZcfA92-wHMgQTU0ynpLxZm5j7XPA',
    appId: '1:361353348856:android:a37a085131f56037ef5d0d',
    messagingSenderId: '361353348856',
    projectId: 'events-manager-f5341',
    storageBucket: 'events-manager-f5341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApsBFmmQmU0R-c0tqQvwcxGZBAdK6830',
    appId: '1:361353348856:ios:0612f8b4f81345f5ef5d0d',
    messagingSenderId: '361353348856',
    projectId: 'events-manager-f5341',
    storageBucket: 'events-manager-f5341.firebasestorage.app',
    iosBundleId: 'com.example.eventsManager',
  );
}
